apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: prison-api
  description: Access to all NOMIS data via this API.
  labels:
    example.com/custom: custom_label_value
  annotations:
    circleci.com/project-slug: github/ministryofjustice/prison-api
  tags:
    - Java
    - Spring Boot
  links:
    - url: https://api.prison.service.justice.gov.uk/health
      title: Health Check
      icon: dashboard
    - url: https://github.com/ministryofjustice/nomis-api-terraform-azure/
      title: Infrastrcutre code
      icon: dashboard
spec:
  type: openapi
  lifecycle: live
  owner: dps-tech-team
  definition:
     $text: https://api.prison.service.justice.gov.uk/api/swagger.json
