apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: HMPPS_Tech_radar_protoype
  description: |
    A proof of concept design for the HMPPS tech rader.
  links:
    - title: Website
      url: https://dashboard.heroku.com/apps/hmpps-tech-radar-v2-prototype
  annotations:
    github.com/project-slug: hmpps-prototype-tech-rader

spec:
  type: Website
  owner: Steven Wilson
  lifecycle: alpha
